### ISSUE TITLE
[Feature Request] GIF Support

### ISSUE THREAD

**Issue by Lachee** [mcrescas/veriv#2]
Excellent image viewer with great basic tools for zooming and viewing images. 
Could this functionality be extended to GIFs and other animated image formats such as WebM or APNG?

**Comment by mcrescas** [comment]
Hi @Lachee -- It should be possible. Do you think that opening the GIF as multiple frames and then using the "video visualization" should be enough for your use case?

Thanks for your kind words :)

**Comment by Lachee** [comment]
Yup! For my use case that will be perfect.

**Comment by mcrescas** [comment]
I have pushed a new version `1.0.2` supporting animated `GIF` and `APNG`. If you find any bugs feel free to tell me :)

**Comment by Lachee** [comment]
seems that none of the images are loading now after an update :c

here is a video showing the issue:
https://i.lu.je/2023/Code_DgDfWIK3gj.mp4

**Comment by mcrescas** [comment]
Are you using Windows? I made one modification and maybe is broken in Windows

**Comment by Lachee** [comment]
yup this works
